version: '3.7'
services:
  seleniumhub:
    image: selenium/hub
    ports: 
      - "4444:4444"
  chromenode:
    image: selenium/node-chrome-debug
    links:
      - "seleniumhub:hub"
    ports:
      - "5900"
    volumes: 
      - "/dev/shm:/dev/shm"
    depends_on:
      - seleniumhub
    environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
            NODE_MAX_SESSION: 4
            NODE_MAX_INSTANCES: 4  
  db:
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
    expose:
      - "3306"
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "my-db:/var/lib/mysql"
  firefoxnode:
    image: selenium/node-firefox-debug
    links: 
      - "seleniumhub:hub"
    ports:
      - "5900"
    volumes:
      - "/dev/shm:/dev/shm"   
    depends_on:
      - seleniumhub 
    environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444 
            NODE_MAX_SESSION: 4
            NODE_MAX_INSTANCES: 4 
  
# Names our volume
volumes:
  my-db: